[theme]
background = "#001908"
primary = "#0D8A08"
secondary = "#1ED760"
title = "#1ED760"
playing = "#000000"
playing_selected = "#000000"
playing_bg = "#92FFBB"
highlight = "#000000"
highlight_bg = "#52824F"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#00AC4C"
statusbar_bg = "#00AC4C"
cmdline = "#FFFFFF"
cmdline_bg = "#000000"
