#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/material/scripts/pywal.sh
bash ~/.config/polybar/launch.sh --material

~/.config/polybar/launch.sh &
compton --config /home/pablo/.config/compton/compton.conf &
feh --bg-fill /home/pablo/Images/Wallpapers/wallpaper1.jpg &
wname L3DG &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
