#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --blocks
bspc monitor -d I II III IV V 
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^6'
bspc rule -a Brave-browser desktop='^7'
bspc rule -a Google-chrome desktop='^8'
bspc rule -a Spotify desktop='^9'
bspc rule -a vlc state=floating
bspc rule -a Pavucontrol desktop='^3'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
